name: Build
on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    bun-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: "Install Dependencies"
              run: bun install

            - name: "Build app"
              run: bun run build

            - uses: softprops/action-gh-release@v2
              with:
                  files: |
                      token-api
